version: "3.9"
services:
  app:
    build:
      context: .
    volumes:
      - .:/core
    ports:
      - 3000:3000
    image: dockerbangladeshbank:dev
    container_name: bb_frontend
    command: npm start
